### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [chelseyeslehc/prj-rev-bwfs-dasmoto#4]
Alternatively, you could use `h2` as the selector for specifying the shared properties among the 3 headings. This could help you avoid some repetition in code:
```css
h2 {
  font-family: Helvetica;
  font-size: 32px;  
  font-weight: bold;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

(Also, don't forget the semi-colon after `font-size: 32px`)

https://github.com/chelseyeslehc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L12-L32
